languages: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
 - '12'
git: 
  depth: 3
script:
  - yarn build
# Who is notified from this process
notifications:
  email:
    recipients:
      - rubbenpad2@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skit-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: build/
  target-branch: gh-pages
  commit_message: 'deploy with travis'
  on:
    branch: master